# Generated by Django 5.2.1 on 2026-05-30 17:51

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


FASHION_TREE = [
    ("MEN'S FASHION", "mens", [
        ("T-Shirts", []),
        ("Shirts", []),
        ("Polos", []),
        ("Jeans", []),
        ("Trousers", []),
        ("Cargo Pants", []),
        ("Shorts", []),
        ("Hoodies & Sweatshirts", []),
        ("Jackets & Coats", []),
        ("Blazers", []),
        ("Suits", []),
        ("Innerwear", []),
        ("Nightwear", []),
        ("Activewear", []),
        ("Traditional Wear", [
            ("Kurtas", []),
            ("Kurta Sets", []),
            ("Sherwanis", []),
        ]),
        ("Footwear", [
            ("Casual Shoes", []),
            ("Formal Shoes", []),
            ("Sports Shoes", []),
            ("Sandals & Floaters", []),
            ("Slippers", []),
        ]),
        ("Accessories", [], True),
    ]),
    ("WOMEN'S FASHION", "womens", [
        ("Ethnic Wear", [
            ("Sarees", []),
            ("Kurtas & Kurtis", []),
            ("Salwar Suits", []),
            ("Lehenga Cholis", []),
            ("Dupattas", []),
        ]),
        ("Western Wear", [
            ("Tops", []),
            ("T-Shirts", []),
            ("Shirts", []),
            ("Dresses", []),
            ("Jumpsuits", []),
            ("Skirts", []),
            ("Jeans", []),
            ("Trousers", []),
        ]),
        ("Lingerie & Sleepwear", []),
        ("Maternity Wear", []),
        ("Activewear", []),
        ("Winter Wear", []),
        ("Footwear", [
            ("Heels", []),
            ("Flats", []),
            ("Sandals", []),
            ("Sneakers", []),
            ("Boots", []),
        ]),
        ("Bags & Accessories", [], True),
    ]),
    ("KIDS FASHION", "kids", [
        ("Boys", [
            ("T-Shirts", []),
            ("Shirts", []),
            ("Jeans", []),
            ("Shorts", []),
            ("Trousers", []),
            ("Ethnic Wear", []),
            ("Nightwear", []),
            ("Winter Wear", []),
        ]),
        ("Girls", [
            ("Dresses", []),
            ("Frocks", []),
            ("Tops & T-Shirts", []),
            ("Skirts", []),
            ("Leggings", []),
            ("Ethnic Wear", []),
            ("Nightwear", []),
            ("Winter Wear", []),
        ]),
        ("Baby Care", [
            ("Newborn Clothing", []),
            ("Rompers", []),
            ("Baby Sets", []),
            ("Baby Essentials", []),
        ]),
        ("Toys", []),
        ("Footwear", [
            ("School Shoes", []),
            ("Casual Shoes", []),
            ("Sandals", []),
            ("Slippers", []),
        ]),
    ]),
    ("ACCESSORIES", "accessories", [
        ("Men's Accessories", [], True),
        ("Women's Accessories", [], True),
        ("Kids Accessories", [], True),
        ("Watches", [], True),
        ("Bags", [], True),
        ("Jewelry", [], True),
        ("Sunglasses", [], True),
        ("Wallets", [], True),
        ("Belts", [], True),
        ("Caps & Hats", [], True),
    ]),
]


def _normalize_node(raw_node):
    name = raw_node[0]
    children = raw_node[1] if len(raw_node) > 1 else []
    under_maintenance = bool(raw_node[2]) if len(raw_node) > 2 else False
    return name, children, under_maintenance


def seed_fashion_categories(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    SubCategory = apps.get_model('store', 'SubCategory')
    FashionCategory = apps.get_model('store', 'FashionCategory')

    def ensure_subcategory(root_category, name):
        existing = SubCategory.objects.filter(
            category=root_category,
            subcategory_name__iexact=name,
        ).first()
        if existing:
            return existing
        return SubCategory.objects.create(category=root_category, subcategory_name=name)

    def create_node(root_category, parent, name, children, under_maintenance, level, sort_order):
        slug = slugify(name)[:160] or f'category-{sort_order}'
        node, _ = FashionCategory.objects.update_or_create(
            parent=parent,
            slug=slug,
            defaults={
                'name': name,
                'root_category': root_category,
                'level': level,
                'sort_order': sort_order,
                'is_active': True,
                'is_under_maintenance': under_maintenance,
            },
        )

        if parent is not None and root_category is not None:
            ensure_subcategory(root_category, name)

        for child_order, child in enumerate(children, start=1):
            child_name, child_children, child_under_maintenance = _normalize_node(child)
            create_node(
                root_category,
                node,
                child_name,
                child_children,
                child_under_maintenance,
                level + 1,
                child_order,
            )

    for root_order, (display_name, legacy_category_name, children) in enumerate(FASHION_TREE, start=1):
        root_category, _ = Category.objects.get_or_create(category_name=legacy_category_name)
        create_node(root_category, None, display_name, children, False, 0, root_order)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_bootstrap_fresh_databases'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionCategory',
            fields=[
                ('fashion_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=160)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_under_maintenance', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.fashioncategory')),
                ('root_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fashion_categories', to='store.category')),
            ],
            options={
                'db_table': 'fashion_categories',
                'ordering': ['root_category__category_name', 'level', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fashion_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.fashioncategory'),
        ),
        migrations.AddConstraint(
            model_name='fashioncategory',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='unique_fashion_category_parent_slug'),
        ),
        migrations.RunPython(seed_fashion_categories, migrations.RunPython.noop),
    ]
