# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_wishlist_addresses_order_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashioncategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fashioncategory',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fashioncategory',
            name='page_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
