# Generated by Codex on 2026-06-02

from django.db import migrations
from django.utils.text import slugify


def align_kids_labels(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    FashionCategory = apps.get_model('store', 'FashionCategory')

    kids_root = Category.objects.filter(category_name__iexact='kids').first()
    if not kids_root:
        return

    kids_fashion_root = FashionCategory.objects.filter(
        root_category=kids_root,
        parent__isnull=True,
    ).order_by('sort_order', 'fashion_category_id').first()
    if not kids_fashion_root:
        return

    replacements = {
        'boys': 'Boys Wear',
        'girls': 'Girls Wear',
    }
    for old_name, new_name in replacements.items():
        category = FashionCategory.objects.filter(
            root_category=kids_root,
            parent=kids_fashion_root,
            name__iexact=old_name,
        ).first()
        if category:
            category.name = new_name
            category.slug = slugify(new_name)[:160]
            category.save(update_fields=['name', 'slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_fashioncategory_card_fields'),
    ]

    operations = [
        migrations.RunPython(align_kids_labels, migrations.RunPython.noop),
    ]
