# Generated by Codex on 2026-06-17

from django.db import migrations, models
from django.utils.text import slugify


GENDER_ROOTS = [
    ('Men', 'mens'),
    ('Women', 'womens'),
    ('Kids', 'kids'),
]

SHARED_GROUPS = [
    ('Casual Wear', [
        'T-Shirts',
        'Polo Shirts',
        'Jeans',
        'Hoodies & Sweatshirts',
        'Shorts',
    ]),
    ('Formal Wear', [
        'Suits',
        'Dress Shirts',
        'Blazers',
        'Dress Trousers',
        'Tuxedos',
    ]),
    ('Footwear', [
        'Sneakers',
        'Boots',
        'Dress Shoes',
        'Loafers',
    ]),
    ('Outerwear', [
        'Overcoats',
        'Trench Coats',
        'Puffer Jackets',
    ]),
    ('Accessories', [
        'Bags',
        'Belts',
        'Watches',
        'Sunglasses',
        'Wallets',
    ]),
]

ACCESSORIES_GROUPS = [
    ('Common For All Genders', [
        'Bags',
        'Watches',
        'Sunglasses',
        'Wallets',
        'Other Future Accessories',
    ]),
]


def _unique_slug(model, name, parent=None, instance=None):
    base_slug = slugify(name)[:150] or 'category'
    slug = base_slug
    counter = 2
    queryset = model.objects.filter(parent=parent, slug=slug)
    if instance is not None:
        queryset = queryset.exclude(pk=instance.pk)
    while queryset.exists():
        suffix = f'-{counter}'
        slug = f'{base_slug[:160 - len(suffix)]}{suffix}'
        counter += 1
        queryset = model.objects.filter(parent=parent, slug=slug)
        if instance is not None:
            queryset = queryset.exclude(pk=instance.pk)
    return slug


def _ensure_node(FashionCategory, root_category, parent, name, level, sort_order, under_maintenance=False):
    slug = slugify(name)[:160] or f'category-{sort_order}'
    node = FashionCategory.objects.filter(parent=parent, slug=slug).first()
    if node is None:
        node = FashionCategory(parent=parent, slug=slug)
    node.name = name
    node.root_category = root_category
    node.level = level
    node.sort_order = sort_order
    node.is_active = True
    node.is_under_maintenance = under_maintenance
    node.save()
    return node


def _ensure_subcategory(SubCategory, category, name):
    return SubCategory.objects.filter(category=category, subcategory_name__iexact=name).first() or SubCategory.objects.create(
        category=category,
        subcategory_name=name,
    )


def seed_root_hierarchy(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    SubCategory = apps.get_model('store', 'SubCategory')
    FashionCategory = apps.get_model('store', 'FashionCategory')
    Product = apps.get_model('store', 'Product')

    leaf_lookup = {}

    for root_order, (display_name, legacy_name) in enumerate(GENDER_ROOTS, start=1):
        legacy_category, _ = Category.objects.get_or_create(category_name=legacy_name)
        root_node = FashionCategory.objects.filter(root_category=legacy_category, parent__isnull=True).order_by('fashion_category_id').first()
        if root_node is None:
            root_node = FashionCategory(parent=None, root_category=legacy_category)
        root_node.name = display_name
        root_node.slug = slugify(display_name)
        root_node.level = 0
        root_node.sort_order = root_order
        root_node.is_active = True
        root_node.is_under_maintenance = False
        root_node.save()

        for group_order, (group_name, leaves) in enumerate(SHARED_GROUPS, start=1):
            group = _ensure_node(FashionCategory, legacy_category, root_node, group_name, 1, group_order)
            leaf_lookup[(legacy_name, slugify(group_name))] = group
            _ensure_subcategory(SubCategory, legacy_category, group_name)
            for leaf_order, leaf_name in enumerate(leaves, start=1):
                leaf = _ensure_node(FashionCategory, legacy_category, group, leaf_name, 2, leaf_order)
                leaf_lookup[(legacy_name, slugify(leaf_name))] = leaf
                _ensure_subcategory(SubCategory, legacy_category, leaf_name)

    accessories_category, _ = Category.objects.get_or_create(category_name='accessories')
    accessories_root = FashionCategory.objects.filter(root_category=accessories_category, parent__isnull=True).order_by('fashion_category_id').first()
    if accessories_root is None:
        accessories_root = FashionCategory(parent=None, root_category=accessories_category)
    accessories_root.name = 'Accessories'
    accessories_root.slug = 'accessories'
    accessories_root.level = 0
    accessories_root.sort_order = 4
    accessories_root.is_active = True
    accessories_root.is_under_maintenance = True
    accessories_root.save()

    common = _ensure_node(FashionCategory, accessories_category, accessories_root, 'Common For All Genders', 1, 1, under_maintenance=True)
    _ensure_subcategory(SubCategory, accessories_category, 'Common For All Genders')
    leaf_lookup[('accessories', 'common')] = common
    for leaf_order, leaf_name in enumerate(ACCESSORIES_GROUPS[0][1], start=1):
        leaf = _ensure_node(FashionCategory, accessories_category, common, leaf_name, 2, leaf_order, under_maintenance=True)
        leaf_lookup[('accessories', slugify(leaf_name))] = leaf
        _ensure_subcategory(SubCategory, accessories_category, leaf_name)

    mapping = {
        ('mens', 't-shirts'): ('mens', 't-shirts'),
        ('mens', 'shirts'): ('mens', 'dress-shirts'),
        ('mens', 'jeans'): ('mens', 'jeans'),
        ('mens', 'accessories'): ('mens', 'accessories'),
        ('womens', 'ethnic wear'): ('womens', 'casual-wear'),
        ('womens', 'western wear'): ('womens', 'casual-wear'),
        ('womens', 'footwear'): ('womens', 'footwear'),
        ('womens', 'bags & accessories'): ('womens', 'accessories'),
        ('womens', 'bags and accessories'): ('womens', 'accessories'),
        ('kids', 't-shirts'): ('kids', 't-shirts'),
        ('kids', 'kids t-shirts'): ('kids', 't-shirts'),
        ('kids', 'dresses'): ('kids', 'formal-wear'),
        ('kids', 'kids dresses'): ('kids', 'formal-wear'),
        ('kids', 'toys'): ('kids', 'accessories'),
        ('kids', 'footwear'): ('kids', 'footwear'),
    }

    for product in Product.objects.select_related('category', 'subcategory').all():
        if not product.slug:
            base_slug = slugify(product.product_name)[:150] or f'product-{product.product_id}'
            slug = base_slug
            counter = 2
            while Product.objects.filter(slug=slug).exclude(product_id=product.product_id).exists():
                suffix = f'-{counter}'
                slug = f'{base_slug[:180 - len(suffix)]}{suffix}'
                counter += 1
            product.slug = slug

        root_name = (product.category.category_name or '').lower()
        sub_name = (product.subcategory.subcategory_name or '').lower()
        target_key = mapping.get((root_name, sub_name)) or (root_name, slugify(sub_name))
        target = leaf_lookup.get(target_key)
        if target:
            product.fashion_category = target
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_align_kids_fashion_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashioncategory',
            name='banner_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.RunPython(seed_root_hierarchy, migrations.RunPython.noop),
    ]
