# Generated by Codex on 2026-06-18

from django.db import migrations
from django.utils.text import slugify


GENDER_ROOTS = [
    ('Men', 'mens'),
    ('Women', 'womens'),
    ('Kids', 'kids'),
]

REQUIRED_TREE = [
    ('Casual Wear', [
        'T-Shirts',
        'Polo Shirts',
        'Jeans',
        'Hoodies & Sweatshirts',
        'Shorts',
        'Dresses',
    ]),
    ('Formal Wear', [
        'Formal Shirts',
        'Suits',
        'Blazers',
        'Dress Trousers',
        'Tuxedos',
    ]),
    ('Ethnic Wear', [
        'Kurtas',
        'Sarees',
        'Lehengas',
        'Sherwanis',
        'Ethnic Dresses',
    ]),
    ('Footwear', [
        'Sneakers',
        'Sandals',
        'Boots',
        'Dress Shoes',
        'Loafers',
    ]),
    ('Accessories', [
        'Bags',
        'Belts',
        'Watches',
        'Sunglasses',
        'Wallets',
        'Toys',
    ]),
]


def _ensure_subcategory(SubCategory, category, name):
    return (
        SubCategory.objects.filter(category=category, subcategory_name__iexact=name).first()
        or SubCategory.objects.create(category=category, subcategory_name=name)
    )


def _find_child(parent, *names):
    slugs = [slugify(name) for name in names]
    return parent.children.filter(slug__in=slugs).order_by('fashion_category_id').first()


def _ensure_node(FashionCategory, root_category, parent, name, level, sort_order):
    slug = slugify(name)
    node = _find_child(parent, name)
    if node is None and name == 'Ethnic Wear':
        node = _find_child(parent, 'Outerwear')
    if node is None and name == 'Formal Shirts':
        node = _find_child(parent, 'Dress Shirts')
    if node is None:
        node = FashionCategory(parent=parent, root_category=root_category, slug=slug)

    node.name = name
    node.slug = slug
    node.root_category = root_category
    node.parent = parent
    node.level = level
    node.sort_order = sort_order
    node.is_active = True
    node.is_under_maintenance = False
    node.save()
    return node


def normalize_required_hierarchy(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    SubCategory = apps.get_model('store', 'SubCategory')
    FashionCategory = apps.get_model('store', 'FashionCategory')
    Product = apps.get_model('store', 'Product')

    leaves = {}

    for root_order, (display_name, legacy_name) in enumerate(GENDER_ROOTS, start=1):
        root_category, _ = Category.objects.get_or_create(category_name=legacy_name)
        root_node = (
            FashionCategory.objects.filter(root_category=root_category, parent__isnull=True)
            .order_by('fashion_category_id')
            .first()
        )
        if root_node is None:
            root_node = FashionCategory(parent=None, root_category=root_category)
        root_node.name = display_name
        root_node.slug = slugify(display_name)
        root_node.root_category = root_category
        root_node.level = 0
        root_node.sort_order = root_order
        root_node.is_active = True
        root_node.is_under_maintenance = False
        root_node.save()

        for main_order, (main_name, sub_names) in enumerate(REQUIRED_TREE, start=1):
            main = _ensure_node(FashionCategory, root_category, root_node, main_name, 1, main_order)
            _ensure_subcategory(SubCategory, root_category, main_name)
            leaves[(legacy_name, slugify(main_name))] = main
            for sub_order, sub_name in enumerate(sub_names, start=1):
                leaf = _ensure_node(FashionCategory, root_category, main, sub_name, 2, sub_order)
                _ensure_subcategory(SubCategory, root_category, sub_name)
                leaves[(legacy_name, slugify(sub_name))] = leaf

    product_targets = {
        ('mens', 't-shirts'): ('mens', 't-shirts'),
        ('mens', 'shirts'): ('mens', 'formal-shirts'),
        ('mens', 'formal shirts'): ('mens', 'formal-shirts'),
        ('mens', 'dress shirts'): ('mens', 'formal-shirts'),
        ('mens', 'jeans'): ('mens', 'jeans'),
        ('mens', 'accessories'): ('mens', 'wallets'),
        ('womens', 'ethnic wear'): ('womens', 'kurtas'),
        ('womens', 'western wear'): ('womens', 'dresses'),
        ('womens', 'footwear'): ('womens', 'sandals'),
        ('womens', 'bags & accessories'): ('womens', 'bags'),
        ('womens', 'bags and accessories'): ('womens', 'bags'),
        ('kids', 't-shirts'): ('kids', 't-shirts'),
        ('kids', 'kids t-shirts'): ('kids', 't-shirts'),
        ('kids', 'dresses'): ('kids', 'ethnic-dresses'),
        ('kids', 'kids dresses'): ('kids', 'ethnic-dresses'),
        ('kids', 'toys'): ('kids', 'toys'),
        ('kids', 'footwear'): ('kids', 'sneakers'),
    }

    for product in Product.objects.select_related('category', 'subcategory', 'fashion_category').all():
        category_name = (product.category.category_name or '').lower()
        subcategory_name = (product.subcategory.subcategory_name or '').lower()
        target_key = product_targets.get((category_name, subcategory_name))

        if target_key is None and product.fashion_category_id:
            current = product.fashion_category
            if current.level >= 2:
                continue
            target_key = (category_name, slugify(current.name or subcategory_name))

        target = leaves.get(target_key) if target_key else None
        if target:
            product.fashion_category = target
            product.subcategory = _ensure_subcategory(SubCategory, product.category, target.name)
            product.save()


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0014_root_fashion_hierarchy'),
    ]

    operations = [
        migrations.RunPython(normalize_required_hierarchy, migrations.RunPython.noop),
    ]
