# Generated by Codex on 2026-06-21

from django.db import migrations


REQUIRED_MAIN_CATEGORIES = {
    'casual wear',
    'formal wear',
    'ethnic wear',
    'footwear',
    'accessories',
}


def hide_nonrequired_main_categories(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    FashionCategory = apps.get_model('store', 'FashionCategory')

    gender_roots = Category.objects.filter(category_name__in=['mens', 'womens', 'kids'])
    for root_category in gender_roots:
        root_node = (
            FashionCategory.objects.filter(root_category=root_category, parent__isnull=True)
            .order_by('fashion_category_id')
            .first()
        )
        if root_node is None:
            continue

        for child in FashionCategory.objects.filter(parent=root_node):
            child.is_active = (child.name or '').strip().lower() in REQUIRED_MAIN_CATEGORIES
            child.save(update_fields=['is_active'])


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0015_required_customer_hierarchy'),
    ]

    operations = [
        migrations.RunPython(hide_nonrequired_main_categories, migrations.RunPython.noop),
    ]
