# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_ensure_all_tables_managed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('uploaded_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.BinaryField()),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploaded_images',
                'managed': True,
            },
        ),
    ]