# Generated by Django 5.2.1 on 2026-06-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_uploadedimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecontent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='kidscategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mencategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pageasset',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='siteasset',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='womencategory',
            options={'managed': True},
        ),
    ]
