# Generated by Codex on 2026-07-25

from django.db import migrations


def normalize_fashion_category_sort_order(apps, schema_editor):
    FashionCategory = apps.get_model('store', 'FashionCategory')
    parent_ids = list(
        FashionCategory.objects.order_by()
        .values_list('parent_id', flat=True)
        .distinct()
    )
    root_ids = list(
        FashionCategory.objects.order_by()
        .filter(parent_id__isnull=True)
        .values_list('root_category_id', flat=True)
        .distinct()
    )

    for root_id in root_ids:
        siblings = FashionCategory.objects.filter(parent_id__isnull=True, root_category_id=root_id).order_by('sort_order', 'fashion_category_id')
        for index, category in enumerate(siblings, start=1):
            if category.sort_order != index:
                category.sort_order = index
                category.save(update_fields=['sort_order'])

    for parent_id in parent_ids:
        if parent_id is None:
            continue
        siblings = FashionCategory.objects.filter(parent_id=parent_id).order_by('sort_order', 'fashion_category_id')
        for index, category in enumerate(siblings, start=1):
            if category.sort_order != index:
                category.sort_order = index
                category.save(update_fields=['sort_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_is_featured_product_rating'),
    ]

    operations = [
        migrations.RunPython(normalize_fashion_category_sort_order, migrations.RunPython.noop),
    ]
